// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvF7D8iqfyXReINIXYz9KP1j46qZJ9lbA',
    appId: '1:1007687234784:web:1874237064a5f95e0d4c85',
    messagingSenderId: '1007687234784',
    projectId: 'schoolxon-d04e5',
    authDomain: 'schoolxon-d04e5.firebaseapp.com',
    storageBucket: 'schoolxon-d04e5.appspot.com',
    measurementId: 'G-WMEPBEV19G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1_loUK7t6jofRUm42X7g8T2OyqUyB7Ms',
    appId: '1:1007687234784:android:2330f482609084fd0d4c85',
    messagingSenderId: '1007687234784',
    projectId: 'schoolxon-d04e5',
    storageBucket: 'schoolxon-d04e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANWGhs6axFOtgM-Gk6RC2M2CN_LaicxvM',
    appId: '1:1007687234784:ios:60b49275de3d47e10d4c85',
    messagingSenderId: '1007687234784',
    projectId: 'schoolxon-d04e5',
    storageBucket: 'schoolxon-d04e5.appspot.com',
    iosBundleId: 'com.example.schoolxon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANWGhs6axFOtgM-Gk6RC2M2CN_LaicxvM',
    appId: '1:1007687234784:ios:60b49275de3d47e10d4c85',
    messagingSenderId: '1007687234784',
    projectId: 'schoolxon-d04e5',
    storageBucket: 'schoolxon-d04e5.appspot.com',
    iosBundleId: 'com.example.schoolxon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvF7D8iqfyXReINIXYz9KP1j46qZJ9lbA',
    appId: '1:1007687234784:web:26638e4fac7da5390d4c85',
    messagingSenderId: '1007687234784',
    projectId: 'schoolxon-d04e5',
    authDomain: 'schoolxon-d04e5.firebaseapp.com',
    storageBucket: 'schoolxon-d04e5.appspot.com',
    measurementId: 'G-VBGCZXFG54',
  );
}
